package sg.org.bcc.attendance.util

import sg.org.bcc.attendance.data.local.entities.Attendee

object DemoData {
    val disneyCharacters = listOf(
        Attendee("D01", "Mickey Mouse", "Mickey"),
        Attendee("D02", "Minnie Mouse", "Minnie"),
        Attendee("D03", "Donald Duck", "Donald"),
        Attendee("D04", "Daisy Duck", "Daisy"),
        Attendee("D05", "Goofy Goof", "Goofy"),
        Attendee("D06", "Pluto Dog", "Pluto"),
        Attendee("D07", "Chipmunk Chip", "Chip"),
        Attendee("D08", "Chipmunk Dale", "Dale"),
        Attendee("D09", "Snow White", "Snow"),
        Attendee("D10", "Cinderella Tremaine", "Cinderella"),
        Attendee("D11", "Aurora Rose", "Aurora"),
        Attendee("D12", "Ariel Triton", "Ariel"),
        Attendee("D13", "Belle Maurice", "Belle"),
        Attendee("D14", "Jasmine Sultan", "Jasmine"),
        Attendee("D15", "Pocahontas Powhatan", "Pocahontas"),
        Attendee("D16", "Fa Mulan", "Mulan"),
        Attendee("D17", "Tiana Rogers", "Tiana"),
        Attendee("D18", "Rapunzel Corona", "Rapunzel"),
        Attendee("D19", "Merida DunBroch", "Merida"),
        Attendee("D20", "Elsa Arendelle", "Elsa"),
        Attendee("D21", "Anna Arendelle", "Anna"),
        Attendee("D22", "Moana Waialiki", "Moana"),
        Attendee("D23", "Simba Lion", "Simba"),
        Attendee("D24", "Nala Lion", "Nala"),
        Attendee("D25", "Timon Meerkat", "Timon"),
        Attendee("D26", "Pumbaa Warthog", "Pumbaa"),
        Attendee("D27", "Mufasa Lion", "Mufasa"),
        Attendee("D28", "Scar Lion", "Scar"),
        Attendee("D29", "Woody Pride", "Woody"),
        Attendee("D30", "Buzz Lightyear", "Buzz"),
        Attendee("D31", "Jessie Cowgirl", "Jessie"),
        Attendee("D32", "Rex Dinosaur", "Rex"),
        Attendee("D33", "Hamm Pig", "Hamm"),
        Attendee("D34", "Slinky Dog", "Slinky"),
        Attendee("D35", "Lightning McQueen", "Lightning"),
        Attendee("D36", "Mater Tow", "Mater"),
        Attendee("D37", "Sally Carrera", "Sally"),
        Attendee("D38", "Doc Hudson", "Doc"),
        Attendee("D39", "Joy Emotion", "Joy"),
        Attendee("D40", "Sadness Emotion", "Sadness"),
        Attendee("D41", "Anger Emotion", "Anger"),
        Attendee("D42", "Fear Emotion", "Fear"),
        Attendee("D43", "Disgust Emotion", "Disgust"),
        Attendee("D44", "Hiro Hamada", "Hiro"),
        Attendee("D45", "Baymax Robot", "Baymax"),
        Attendee("D46", "Stitch Experiment", "Stitch"),
        Attendee("D47", "Lilo Pelekai", "Lilo"),
        Attendee("D48", "Peter Pan", "Peter"),
        Attendee("D49", "Wendy Darling", "Wendy"),
        Attendee("D50", "Captain Hook", "Hook")
    )
}
